### ISSUE TITLE
Can you give me some help?

### ISSUE THREAD

**Issue by mengxianq** [wanghuogen/ConGestureChallenge4ICCV#1]
Hello，I am a graduate student at Hebei University of Technology. I am currently studying sign language recognition. I saw your research content in the ccf newsletter and found the code on GitHub, but without the database,I found the URL of the original database, but it is no longer available. Can you give me the information of the database? Thank you very much.

**Comment by wanghuogen** [comment]
@mengxianq I think you can get the whole dataset from Jun Wan's homepage. If it is not available, you can send email to Jun Wan. He will help you get the dataset.

**Comment by wanghuogen** [comment]
@mengxianq http://www.cbsr.ia.ac.cn/users/jwan/research.html
